import Header from "@/components/common/header/Header";
import MuiThemeProvider from "@/components/common/theme-provider/MuiThemeProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import { Paper } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* For MUI Icons */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body>
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            <ReduxProvider>
              <Header />
              <Paper sx={{ mt: 6 }}>{children}</Paper>
            </ReduxProvider>
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
